# Generated by Django 4.0.6 on 2022-08-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster_dir_path', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('runtime', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('max_price', models.IntegerField()),
            ],
        ),
    ]
