# Generated by Django 4.0.6 on 2022-08-24 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('culture_circle_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
